### PR TITLE
Added global settings to plugin

### PR DESCRIPTION
**Pull request by Kathrin84**
I'm making this pull request on behalf of Alexander Bias.

This is a fix to issues #16 and #17.
I added a setting possibility to decide if the titles should be forced
to use or not (then the summary would be taken if the default title is
set and the summary is not empty). This should fix issue #17
And then I added a settings.php to enable global settings. There the
admin can set the default value and is able to lock the settings so
that teachers cannot change value anymore. This setting simply will not
be presented to the teacher in the individual block settings. This
should fix and extent issue #16.

Concerning the strings: I tried my best with it. If you have a better idea for naming or description texts, feel free to change them.

### CODE REVIEW

**Comment by mudrd8mz** [comment]
Thanks a lot for submitting this pull request. I have it in my TODO inbox and I'll try to get to it as soon as possible. Thanks for understanding.

**Comment by mudrd8mz** [comment]
Hi @Kathrin84 can you please config you have received my feedback on the patch?

**Comment by Kathrin84** [comment]
Hi David, I received your feedback, however did not found time to deal with them yet. Sorry for that.
The next weeks I'm on holiday, so it will need some more time...
Cheers, Kathrin

**Comment by Kathrin84** [comment]
Hi David, I'm back from holidays. I saw that you released a new version that fixes the issue with the standard headings and summary usage.
Now I'm not quite sure if I should do something considering this pull request?

For me, your improvement looks very fine in usage.

Cheers, Kathrin

**Comment by mudrd8mz** [comment]
Thanks for the confirmation Kathrin. I am closing this now.

**Pull request closed without merging**
